// Fake but plausible game data — Claude Code will replace this with real chess.com pulls.
window.GAMES_DATA = [
  {
    id: "g01", rank: 1, score: 100,
    white: { name: "tactic", rating: 3077 },
    black: { name: "Navi_NazarPro", rating: 3089 },
    result: "1/2-1/2", timeControl: "Bullet", eco: "A04",
    date: "17 May 2026",
    dims: { drama: 100, clock: 100, brilliancy: 88, sacrifice: 50, endgame: 72, upset: 18, rarity: 64 },
    moves: 67, mateIn: null,
    opening: "Réti Opening",
    chessComUrl: "#",
    highlight: "Échange de sacrifices en bullet, finale folle.",
  },
  {
    id: "g02", rank: 2, score: 96,
    white: { name: "Philippians46", rating: 3200 },
    black: { name: "Navi_NazarPro", rating: 3106 },
    result: "0-1", timeControl: "Bullet", eco: "A10",
    date: "16 May 2026",
    dims: { drama: 92, clock: 88, brilliancy: 95, sacrifice: 82, endgame: 40, upset: 22, rarity: 58 },
    moves: 41,
    opening: "English Opening",
    chessComUrl: "#",
    highlight: "Sacrifice de dame au coup 28, mat forcé en 7.",
  },
  {
    id: "g03", rank: 3, score: 94,
    white: { name: "MagnusCarlsen", rating: 3356 },
    black: { name: "Hikaru", rating: 3336 },
    result: "1-0", timeControl: "Blitz", eco: "C42",
    date: "15 May 2026",
    dims: { drama: 78, clock: 60, brilliancy: 99, sacrifice: 90, endgame: 88, upset: 8, rarity: 30 },
    moves: 52,
    opening: "Petroff Defence",
    chessComUrl: "#",
    highlight: "Manœuvre de cavalier digne d'un puzzle.",
  },
  {
    id: "g04", rank: 4, score: 92,
    white: { name: "WorriedEgg", rating: 3400 },
    black: { name: "SatoruGojoUltra", rating: 3402 },
    result: "1-0", timeControl: "Bullet", eco: "B12",
    date: "15 May 2026",
    dims: { drama: 96, clock: 100, brilliancy: 70, sacrifice: 88, endgame: 12, upset: 4, rarity: 70 },
    moves: 38,
    opening: "Caro-Kann, Advance",
    chessComUrl: "#",
    highlight: "Trois drapeaux à 0.3s, victoire au flag.",
  },
  {
    id: "g05", rank: 5, score: 89,
    white: { name: "BerserkWerewolf", rating: 3297 },
    black: { name: "Elfangm2", rating: 3303 },
    result: "0-1", timeControl: "Blitz", eco: "E60",
    date: "14 May 2026",
    dims: { drama: 70, clock: 44, brilliancy: 96, sacrifice: 100, endgame: 80, upset: 28, rarity: 52 },
    moves: 44,
    opening: "King's Indian Defence",
    chessComUrl: "#",
    highlight: "Double sacrifice de tour en milieu de partie.",
  },
  {
    id: "g06", rank: 6, score: 87,
    white: { name: "legendisback1", rating: 3255 },
    black: { name: "LiamPutnam2008", rating: 3302 },
    result: "1-0", timeControl: "Rapid", eco: "D02",
    date: "13 May 2026",
    dims: { drama: 60, clock: 30, brilliancy: 78, sacrifice: 44, endgame: 96, upset: 65, rarity: 80 },
    moves: 84,
    opening: "London System",
    chessComUrl: "#",
    highlight: "Finale tour contre fou et cavalier, 30 coups.",
  },
  {
    id: "g07", rank: 7, score: 84,
    white: { name: "JingtianWu", rating: 3305 },
    black: { name: "SpeedofLight0", rating: 3262 },
    result: "1/2-1/2", timeControl: "Bullet", eco: "B90",
    date: "13 May 2026",
    dims: { drama: 88, clock: 92, brilliancy: 60, sacrifice: 70, endgame: 66, upset: 12, rarity: 38 },
    moves: 92,
    opening: "Sicilian, Najdorf",
    chessComUrl: "#",
    highlight: "Perpétuel après une attaque vénéneuse.",
  },
  {
    id: "g08", rank: 8, score: 82,
    white: { name: "Oleksandr_Bortnyk", rating: 3271 },
    black: { name: "GHANDEEVAM2003", rating: 3288 },
    result: "1-0", timeControl: "Blitz", eco: "C65",
    date: "12 May 2026",
    dims: { drama: 64, clock: 50, brilliancy: 88, sacrifice: 60, endgame: 78, upset: 18, rarity: 42 },
    moves: 56,
    opening: "Ruy Lopez, Berlin",
    chessComUrl: "#",
    highlight: "Manœuvre positionnelle de manuel.",
  },
  {
    id: "g09", rank: 9, score: 80,
    white: { name: "gurelediz", rating: 3288 },
    black: { name: "tactic", rating: 3278 },
    result: "0-1", timeControl: "Bullet", eco: "B22",
    date: "12 May 2026",
    dims: { drama: 76, clock: 84, brilliancy: 72, sacrifice: 38, endgame: 22, upset: 16, rarity: 46 },
    moves: 47,
    opening: "Sicilian, Alapin",
    chessComUrl: "#",
    highlight: "Renversement en zeitnot, le coup 41 change tout.",
  },
  {
    id: "g10", rank: 10, score: 78,
    white: { name: "Hikaru", rating: 3336 },
    black: { name: "MagnusCarlsen", rating: 3356 },
    result: "1/2-1/2", timeControl: "Rapid", eco: "D37",
    date: "11 May 2026",
    dims: { drama: 54, clock: 28, brilliancy: 84, sacrifice: 30, endgame: 92, upset: 6, rarity: 24 },
    moves: 78,
    opening: "Queen's Gambit Declined",
    chessComUrl: "#",
    highlight: "Finale de pièces lourdes, précision chirurgicale.",
  },
  {
    id: "g11", rank: 11, score: 76,
    white: { name: "Philippians46", rating: 3200 },
    black: { name: "BerserkWerewolf", rating: 3297 },
    result: "1-0", timeControl: "Bullet", eco: "B01",
    date: "10 May 2026",
    dims: { drama: 70, clock: 78, brilliancy: 66, sacrifice: 88, endgame: 18, upset: 36, rarity: 56 },
    moves: 33,
    opening: "Scandinavian Defence",
    chessComUrl: "#",
    highlight: "Mat à l'étouffée sur l'aile dame.",
  },
  {
    id: "g12", rank: 12, score: 74,
    white: { name: "SatoruGojoUltra", rating: 3402 },
    black: { name: "WorriedEgg", rating: 3400 },
    result: "1-0", timeControl: "Blitz", eco: "B12",
    date: "10 May 2026",
    dims: { drama: 50, clock: 36, brilliancy: 80, sacrifice: 26, endgame: 70, upset: 10, rarity: 60 },
    moves: 64,
    opening: "Caro-Kann",
    chessComUrl: "#",
    highlight: "Ouverture rare jouée à très haut niveau.",
  },
  {
    id: "g13", rank: 13, score: 72,
    white: { name: "tactic", rating: 3278 },
    black: { name: "gurelediz", rating: 3288 },
    result: "1-0", timeControl: "Bullet", eco: "C50",
    date: "9 May 2026",
    dims: { drama: 80, clock: 86, brilliancy: 54, sacrifice: 40, endgame: 14, upset: 20, rarity: 28 },
    moves: 36,
    opening: "Italian Game",
    chessComUrl: "#",
    highlight: "Attaque directe, mat à découvert.",
  },
  {
    id: "g14", rank: 14, score: 70,
    white: { name: "Elfangm2", rating: 3303 },
    black: { name: "JingtianWu", rating: 3305 },
    result: "0-1", timeControl: "Rapid", eco: "E20",
    date: "9 May 2026",
    dims: { drama: 44, clock: 22, brilliancy: 76, sacrifice: 36, endgame: 88, upset: 14, rarity: 48 },
    moves: 71,
    opening: "Nimzo-Indian",
    chessComUrl: "#",
    highlight: "Pion passé créé au coup 52, conversion propre.",
  },
  {
    id: "g15", rank: 15, score: 68,
    white: { name: "SpeedofLight0", rating: 3262 },
    black: { name: "Oleksandr_Bortnyk", rating: 3271 },
    result: "1/2-1/2", timeControl: "Bullet", eco: "C00",
    date: "8 May 2026",
    dims: { drama: 66, clock: 80, brilliancy: 58, sacrifice: 24, endgame: 36, upset: 10, rarity: 34 },
    moves: 52,
    opening: "French Defence",
    chessComUrl: "#",
    highlight: "Trois fois la position pour le nul.",
  },
];

// Tags for player chips
window.PLAYERS = [
  { name: "SatoruGojoUltra", rating: 3402 },
  { name: "WorriedEgg", rating: 3400 },
  { name: "Philippians46", rating: 3377 },
  { name: "MagnusCarlsen", rating: 3356 },
  { name: "Hikaru", rating: 3336 },
  { name: "JingtianWu", rating: 3305 },
  { name: "Elfangm2", rating: 3303 },
  { name: "LiamPutnam2008", rating: 3302 },
  { name: "BerserkWerewolf", rating: 3297 },
  { name: "GHANDEEVAM2003", rating: 3288 },
  { name: "gurelediz", rating: 3288 },
  { name: "tactic", rating: 3278 },
  { name: "Oleksandr_Bortnyk", rating: 3271 },
  { name: "SpeedofLight0", rating: 3262 },
  { name: "legendisback1", rating: 3255 },
];

// Dimension definitions
window.DIMENSIONS = [
  { key: "sacrifice", label: "Sacrifice", short: "SAC" },
  { key: "drama",     label: "Drama",     short: "DRM" },
  { key: "brilliancy",label: "Brilliancy",short: "BRI" },
  { key: "clock",     label: "Clock pressure", short: "CLK" },
  { key: "endgame",   label: "Endgame",   short: "END" },
  { key: "upset",     label: "Upset",     short: "UPS" },
  { key: "rarity",    label: "Rarity",    short: "RAR" },
];
